"""""
" Maintainer:
"       Ethan Stoneman - @estoneman
"
" Sections:
"    -> General
"    -> Options
"    -> Settings
"    -> Plugins (managed via Plug)
"    -> Colors
"    -> Maps
"""""

"""""
" => General
"""""
" enables lexical highlighting
syntax enable
" enable filetype plugins
filetype plugin on
filetype indent on
let mapleader = ","

"""""
" => Options
"""""
" my statusline (see $XDG_CONFIG_HOME/autoload/statusline.vim)
set statusline=%{%statusline#RegOrNetrw()%}
" i live in tmux
set term=tmux-256color
" set character encoding
set enc=utf-8
" expand tabs, enable autoindent, and set textwidth to 80 respectively
set et sw=4 ts=4 ai tw=80
" relative line numbering
set nu rnu
" disable swapfile
set noswapfile
" disable backup
set nobackup
" don't keep modified buffers open when navigating
set hidden
" set scrolloff
set so=8
" pretty cool command line completion
set wildmenu
" mini pop-up menu of completions
set wildoptions=pum
" ignore case when searching
set ignorecase
" when searching try to be smart about letter case
set smartcase
" highlight search matches
set hlsearch
" only show next match when searching
set incsearch
" add extra column to the left of buffers
set foldcolumn=1

"""""
" => Settings
"""""
let g:netrw_banner=0
let g:netrw_liststyle=3

"""""
" => Plugins
"""""
call plug#begin()

" list desired plugins here
Plug 'rose-pine/vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()

"""""
" => Colors
"""""
colorscheme rosepine
set bg=dark
" make background of vim transparent
hi Normal guibg=NONE ctermbg=NONE

"""""
" => Maps
"""""
func! s:OpenNetrw(opts) abort
    " opts:
    "   cols (Number): number of columns to resize netrw window
    "   stay (bool): whether to stay in netrw window or not
    let l:cols = get(a:opts, 'cols')
    let l:stay = get(a:opts, 'stay')
    let l:edit_window = 1

    Lexplore
    exe "vert res " .. l:cols
    for i in range(winnr(), winnr('$'))
        let l:modifiable = getbufvar(winbufnr(i), '&modifiable')
        if l:modifiable == 1
            let l:edit_window = i
            break
        endif
    endfor

    exe 'NetrwC ' .. l:edit_window

    if !l:stay
        exe l:edit_window .. "wincmd w"
    endif
endfunc

func! s:CloseNetrw() abort
    if &filetype ==# 'netrw'
        close
    else
        let l:left = winnr('h')
        if l:left != winnr()
            execute l:left .. 'close'
        endif
    endif
endfunc

" i like navigating my projects like this for now
nnoremap <silent> <leader>Ex :call <SID>OpenNetrw({'cols': -35, 'stay': v:false})<cr>
" same as above, but stay in netrw
nnoremap <silent> <leader>Ed :call <SID>OpenNetrw({'cols': -35, 'stay': v:true})<cr>
" reverse the above action
nnoremap <silent> <leader>ex :call <SID>CloseNetrw()<cr>

" beast of a map this one is
nmap <leader>w :w!<cr>
" disable highlighting (i use when i'm done searching)
nmap <silent> <leader><c-h> :noh<cr>
" quick quit all windows (after writing all modifiable buffers of course)
nmap <silent> <leader>qa :wa<cr>:qa<cr>
